# Generated by Django 5.1.1 on 2024-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='app.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='meals', to='app.meal'),
        ),
    ]
